"""
Django settings for rivikiwi project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import logging
from pathlib import Path
from environ import Env
from email import charset

charset.add_charset('utf-8', charset.QP, charset.QP, 'utf-8')

env = Env()
env.read_env()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yg3hg+oze@8rx7%=%tnsz*fok%7m_uj2gykg%c^m^h=k-okb+s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.yandex',

    #django apps
    'phonenumber_field',
    "debug_toolbar",
    'captcha',
    
    # our apps
    'products',
    'users',
    'main',
    'reviews',
    'wishlist',
]

PHONENUMBER_DB_FORMAT = 'NATIONAL' # Формат для хранения в базе
PHONENUMBER_DEFAULT_FORMAT = 'INTERNATIONAL' # Формат по умолчанию для вывода
PHONENUMBER_DEFAULT_REGION = 'BY' # Ваш регион по умолчанию (например, RU, US, GB)


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'rivikiwi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

INTERNAL_IPS = [
    '127.0.0.1',
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": BASE_DIR / 'cache',
    }
}

WSGI_APPLICATION = 'rivikiwi.wsgi.application'


DATABASES = {  
    'default': {  
        'ENGINE': 'django.db.backends.postgresql',  
        'NAME': env('DATABASE_NAME'),  
        'USER': env('USER'),  
        'PASSWORD': env('DATABASE_PASSWORD'),  # пароль  
    }  
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

LOGIN_REDIRECT_URL='/'
LOGIN_URL = '/user/login/'

ACCOUNT_LOGIN_METHODS = {'email'}

# ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static/']

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'users.User'

SOCIALACCOUNT_LOGIN_ON_GET=True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': env('OAUTH_GOOGLE_CLIENT_ID'),
            'secret': env('OAUTH_GOOGLE_SECRET'),
        }
    },
    'yandex': {
        'APP': {
            'client_id': env('OAUTH_YANDEX_CLIENT_ID'),
            'secret': env('OAUTH_YANDEX_SECRET'),
        }
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_HOST ="smtp.yandex.ru"
EMAIL_PORT = 465
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_USE_SSL = True


DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

LOG_DIR = BASE_DIR / 'logs'
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "detailed": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "standard": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": 'logging.handlers.TimedRotatingFileHandler',
            "when":"midnight",
            "filename": os.path.join(LOG_DIR, 'django.log'),
            "formatter":"detailed",
        },
        'main_app': {
            'level': 'DEBUG',
            "class": 'logging.handlers.TimedRotatingFileHandler',
            "when":"midnight",
            'filename': os.path.join(LOG_DIR, "main.log"),
            'backupCount':1,
            'formatter': 'standard',
        },
        'users_app': {
            'level': "DEBUG",
            "class": 'logging.handlers.TimedRotatingFileHandler',
            "when":"midnight",
            'filename': os.path.join(LOG_DIR, "users.log"),
            'formatter': 'detailed',
        },
        'wishlist_app': {
            'level': "DEBUG",
            "class": 'logging.handlers.TimedRotatingFileHandler',
            "when":"midnight",
            'filename': os.path.join(LOG_DIR, "wishlist.log"),
            'formatter': 'detailed',
        },
        'reviews_app': {
            'level': "DEBUG",
            "class": 'logging.handlers.TimedRotatingFileHandler',
            "when":"midnight",
            'filename': os.path.join(LOG_DIR, "reviews.log"),
            'formatter': 'detailed',
        },
        'products_app': {
            'level': "DEBUG",
            "class": 'logging.handlers.TimedRotatingFileHandler',
            "when":"midnight",
            'filename': os.path.join(LOG_DIR, "products.log"),
            'formatter': 'detailed',
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "propagate": True,
        },
        "main_app": {
            "handlers": ["main_app"],
            "level": "DEBUG",
            "propagate": True,
        },
        "users_app": {
            "handlers": ["users_app"],
            "level": "DEBUG",
            "propagate": True,
        },
        "wishlist_app": {
            "handlers": ["wishlist_app"],
            "level": "DEBUG",
            "propagate": True,
        },
        "reviews_app": {
            "handlers": ["reviews_app"],
            "level": "DEBUG",
            "propagate": True,
        },
        "products_app": {
            "handlers": ["products_app"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}